apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: carassius
  name: github-actions-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["create", "update", "delete", "get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: ["create", "update", "delete", "get", "list", "watch", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "update", "delete", "get", "list", "watch", "patch"]
