apiVersion: apps/v1
kind: Deployment
metadata:
  name: carassius-producer
  labels:
    app: carassius-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carassius-producer
  template:
    metadata:
      labels:
        app: carassius-producer
    spec:
      containers:
        - name: producer
          image: nikitades/carassius-producer:latest
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "150Mi"
              cpu: "100m"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: producer-secret
                  key: database-url
