apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
type: Opaque
stringData:
  token: replaceme
  channels: replaceme
  database-url: replaceme
  proxy-username: replaceme
  proxy-country: replaceme
  proxy-password: replaceme
  proxy-hostname: replaceme
  proxy-port: replaceme
